---
- name: pull cloud provider specific vars
  include_vars: "{{ _cloud_provider | default('bare') }}.yml"

- name: Run os_family specific tasks
  include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Create /usr/share/java directory
  file:
    path: /usr/share/java
    state: directory
    mode: 0755

- name: find out if file has already been downloaded
  stat:
    path: /usr/share/java/mysql-connector-java.jar
  register: mysql_connector_java

- name: Download MySQL Connector/J 
  get_url:
    url: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.48.zip
    dest: "~/mysql-connector-java.zip"
    checksum: "md5:5da24facd99964f296ecde32abcd2384"
    mode: 0644
  when: not mysql_connector_java.stat.exists

- name: Extract MySQL Connector/J zip file
  unarchive:
    src: "~/mysql-connector-java.zip"
    dest: "~"
    copy: no
  when: not mysql_connector_java.stat.exists

- name: Copy MySQL Connector/J jar file to correct location
  copy:
    src: "~/mysql-connector-java-5.1.48/mysql-connector-java-5.1.48.jar"
    dest: /usr/share/java/mysql-connector-java.jar
    mode: 0644
    remote_src: yes
  when: not mysql_connector_java.stat.exists



- name: passwordless root login
  shell: |
    cat /home/centos/.ssh/authorized_keys > /root/.ssh/authorized_keys
    chmod 400 /root/.ssh/authorized_keys
    # ssh-keyscan -H `hostname` >> ~/.ssh/known_hosts
    sed -i 's/.*PermitRootLogin.*/PermitRootLogin without-password/' /etc/ssh/sshd_config
    systemctl restart sshd