---
- name: Disable THP now 
  shell: |
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
    echo never > /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable THP at boot
  lineinfile:
    path: "/etc/rc.d/rc.local"
    line: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

- name: Disable THP at boot
  lineinfile:
    path: "/etc/rc.d/rc.local"
    line: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"

- name: Update VM swappiness
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    reload: yes

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Add the preferred Chrony/NTP server
  lineinfile:
    path: "{{ ntp_conf }}"
    line: "{{ ntp_server }}"


- name: restart chronyd/ntp
  service:
    name: "{{ ntp_deamon }}"
    state: restarted

- name: Install the required packages
  yum:
    name: 
      - java-1.8.0-openjdk-devel
      - vim
      - wget
      - curl
      - git
      - unzip
      - bind-utils
      - rng-tools
      - epel-release
    state: latest
    
- name: Install python-pip 
  yum:
    name: 
      - python-pip
    state: latest

- name: copy rng service descriptor
  copy:
    src: "/usr/lib/systemd/system/rngd.service"
    dest: "/etc/systemd/system/"
    remote_src: yes

- name: Ensure that rngd is running and enabled
  service:
    daemon_reload: yes
    name: rngd
    state: restarted
    enabled: yes
    
- name: Disable SELinux enforcement
  selinux:
    state: disabled

- name: Stop and disable firewalld
  systemd:
    name: "firewalld"
    state: stopped
    enabled: no
  ignore_errors: yes