---
- name: Run os_family specific tasks
  include_tasks: "{{ ansible_facts.os_family | lower }}.yml"

- name: Set kdc.conf
  template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    backup: yes

# - name: Set krb5.conf
#   template:
#     src: krb5.conf.j2
#     dest: /etc/krb5.conf
#     backup: yes

- name: Create KDC database
  command: "/usr/sbin/kdb5_util create -s -P {{ krb5_kdc_master_passwd }}"
  args:
    creates: /var/kerberos/krb5kdc/principal

- name: Set kadm5.acl
  template:
    src: kadm5.acl.j2
    dest: /var/kerberos/krb5kdc/kadm5.acl
    backup: yes

# TODO: should this be here? it's CM specific
- name: Create Cloudera Manager admin principal
  command: /usr/sbin/kadmin.local -q "addprinc -pw {{ krb5_kdc_admin_passwd }} {{ krb5_kdc_admin_user }}"

- name: Start Kerberos
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - krb5kdc
    - kadmin

