---
- name: Download CM repo file
  get_url:
    url: "{{ cdpdc.cm.repo_file }}"
    dest: /etc/yum.repos.d/

- name: Install the Cloudera Manager Server packages
  yum:
    name: 
      - cloudera-manager-agent 
      - cloudera-manager-daemons 
      - cloudera-manager-server
    state: latest

